// Mapping ISO 3166-1 alpha-2 → nom français usuel.
// Liste pragmatique : pays susceptibles d'apparaître dans les cartes HistoryDex
// (couvrant les 10 régions historiques). Ajouter au fil des besoins.

const COUNTRY_FR: Record<string, string> = {
  // Europe occidentale
  FR: "France",
  GB: "Royaume-Uni",
  IE: "Irlande",
  ES: "Espagne",
  PT: "Portugal",
  IT: "Italie",
  DE: "Allemagne",
  AT: "Autriche",
  CH: "Suisse",
  NL: "Pays-Bas",
  BE: "Belgique",
  LU: "Luxembourg",
  DK: "Danemark",
  NO: "Norvège",
  SE: "Suède",
  FI: "Finlande",
  IS: "Islande",
  VA: "Vatican",
  GI: "Gibraltar",
  // Europe orientale & Balkans
  PL: "Pologne",
  CZ: "Tchéquie",
  SK: "Slovaquie",
  HU: "Hongrie",
  RO: "Roumanie",
  BG: "Bulgarie",
  GR: "Grèce",
  RS: "Serbie",
  HR: "Croatie",
  SI: "Slovénie",
  BA: "Bosnie-Herzégovine",
  AL: "Albanie",
  MK: "Macédoine du Nord",
  ME: "Monténégro",
  XK: "Kosovo",
  EE: "Estonie",
  LV: "Lettonie",
  LT: "Lituanie",
  // Russie & Asie centrale
  RU: "Russie",
  UA: "Ukraine",
  BY: "Biélorussie",
  MD: "Moldavie",
  GE: "Géorgie",
  AM: "Arménie",
  AZ: "Azerbaïdjan",
  KZ: "Kazakhstan",
  UZ: "Ouzbékistan",
  TM: "Turkménistan",
  KG: "Kirghizistan",
  TJ: "Tadjikistan",
  AF: "Afghanistan",
  IR: "Iran",
  // Proche-Orient & Méditerranée orientale
  TR: "Turquie",
  SY: "Syrie",
  LB: "Liban",
  IL: "Israël",
  PS: "Palestine",
  JO: "Jordanie",
  IQ: "Irak",
  EG: "Égypte",
  SA: "Arabie saoudite",
  YE: "Yémen",
  OM: "Oman",
  AE: "Émirats arabes unis",
  QA: "Qatar",
  BH: "Bahreïn",
  KW: "Koweït",
  CY: "Chypre",
  // Afrique hors Égypte
  MA: "Maroc",
  DZ: "Algérie",
  TN: "Tunisie",
  LY: "Libye",
  SD: "Soudan",
  SS: "Soudan du Sud",
  ET: "Éthiopie",
  ER: "Érythrée",
  DJ: "Djibouti",
  SO: "Somalie",
  KE: "Kenya",
  UG: "Ouganda",
  TZ: "Tanzanie",
  RW: "Rwanda",
  BI: "Burundi",
  CD: "République démocratique du Congo",
  CG: "République du Congo",
  CF: "République centrafricaine",
  CM: "Cameroun",
  GA: "Gabon",
  GQ: "Guinée équatoriale",
  TD: "Tchad",
  NE: "Niger",
  NG: "Nigéria",
  BJ: "Bénin",
  TG: "Togo",
  GH: "Ghana",
  CI: "Côte d'Ivoire",
  BF: "Burkina Faso",
  ML: "Mali",
  SN: "Sénégal",
  GM: "Gambie",
  GN: "Guinée",
  GW: "Guinée-Bissau",
  SL: "Sierra Leone",
  LR: "Liberia",
  MR: "Mauritanie",
  CV: "Cap-Vert",
  ZA: "Afrique du Sud",
  NA: "Namibie",
  BW: "Botswana",
  ZW: "Zimbabwe",
  ZM: "Zambie",
  MW: "Malawi",
  MZ: "Mozambique",
  MG: "Madagascar",
  AO: "Angola",
  // Asie de l'Est
  CN: "Chine",
  JP: "Japon",
  KR: "Corée du Sud",
  KP: "Corée du Nord",
  MN: "Mongolie",
  TW: "Taïwan",
  HK: "Hong Kong",
  // Asie du Sud
  IN: "Inde",
  PK: "Pakistan",
  BD: "Bangladesh",
  NP: "Népal",
  BT: "Bhoutan",
  LK: "Sri Lanka",
  MV: "Maldives",
  // Asie du Sud-Est & Pacifique
  VN: "Vietnam",
  LA: "Laos",
  KH: "Cambodge",
  TH: "Thaïlande",
  MM: "Birmanie",
  MY: "Malaisie",
  SG: "Singapour",
  ID: "Indonésie",
  PH: "Philippines",
  BN: "Brunei",
  TL: "Timor oriental",
  AU: "Australie",
  NZ: "Nouvelle-Zélande",
  PG: "Papouasie-Nouvelle-Guinée",
  FJ: "Fidji",
  PF: "Polynésie française",
  RE: "La Réunion",
  MU: "Maurice",
  FM: "États fédérés de Micronésie",
  SB: "Îles Salomon",
  // Amériques précolombiennes & latines
  MX: "Mexique",
  GT: "Guatemala",
  BZ: "Belize",
  HN: "Honduras",
  SV: "Salvador",
  NI: "Nicaragua",
  CR: "Costa Rica",
  PA: "Panama",
  BS: "Bahamas",
  CU: "Cuba",
  HT: "Haïti",
  DO: "République dominicaine",
  JM: "Jamaïque",
  PR: "Porto Rico",
  CO: "Colombie",
  VE: "Venezuela",
  EC: "Équateur",
  PE: "Pérou",
  BO: "Bolivie",
  CL: "Chili",
  AR: "Argentine",
  UY: "Uruguay",
  PY: "Paraguay",
  BR: "Brésil",
  GY: "Guyana",
  SR: "Suriname",
  // Amérique du Nord
  US: "États-Unis",
  CA: "Canada",
};

export function countryNameFr(code: string | null | undefined): string | null {
  if (!code) return null;
  return COUNTRY_FR[code.toUpperCase()] ?? null;
}
